### ISSUE TITLE
Wrong behavior when fragment applied on item with styled text in slide mode

### ISSUE THREAD

**Issue by PeterDaveHello** [hackmdio/hackmd#287]
The fragment on the item with styled text will have strange behavior, bug confirmed with @jackycute

Example:
```markdown
## What can students do?

- Bug report (as detail as possible) <!-- .element: class="fragment" data-fragment-index="1" -->
- Bug reproduce (**confirm the reported bugs exist**) <!-- .element: class="fragment" data-fragment-index="2" -->
- Test the new features (and you may find bugs!) <!-- .element: class="fragment" data-fragment-index="3" -->
```

**Comment by SISheogorath** [comment]
Needs some research of caused by HackMD code or by upstream (and is probably solved with an update of revealJS)

**Comment by ccoenen** [comment]
I added your markup to this document:
https://hackmd-ce.herokuapp.com/JdwZyUKJSRWwkmEL9cRj1A#

this is still an issue, I'd say: https://hackmd-ce.herokuapp.com/p/rkkXJXez7#/
